baseURL: https://asankah.github.io/
languageCode: en-us
title: "Asanka Herath"
theme: kiss-em
ignoreFiles: [ "content/sources/*", "content/drafts/*" ]
googleAnalytics: UA-169355711-1
enableGitInfo: true
enableRobotsTXT: true
params:
        rss:
                enable: true
                includeContent: true
                authorName: "Asanka Herath"
                authorEmail: "asanka@gmail.com"
        social:
                twitter: "@asankah"
                github: asankah
                email: "asanka@gmail.com"
                rss: "index.xml"
                config:
                        platforms:
                                - "twitter"
                                - "github"
                                - "email"
                                - "rss"
taxonomies:
        tag: "tags"

